#! /usr/bin/env bash

#Sudo Failsafe
if [[ $EUID -ne 0 ]]; then
  echo 'Please run as root (sudo $0)' >&2
  exit 1
fi

#Users
#Variables
#Ubuntu Prctice
#Admins=('perry' 'carlos' 'kan' 'alice' 'josefina')
#Standard=('jaimie' 'adalbern' 'amayas' 'fabienne' 'mariya' 'cornelius' 'harold' 'taran' 'felix' 'angela' 'rais' 'miriam' 'aldo' 'timothy' 'leilani' 'viktor' 'linda' 'jeanne' 'martin' 'josef' 'roger' 'stacy' 'suzy' 'liz')
Admins=(' ')
Standard=(' ')
Allowed_Users=("${Admins[@]}" "${Standard[@]}")
Users=($(cut -d: -f1 /etc/passwd))
#functions
elevate() { usermod -aG sudo "$1"; }
demote()  { gpasswd -d "$1" sudo; }
remove()  { userdel -r "$1"; }
password() { echo "$1:N!w0tC0ug@rS2025" | chpasswd; }
#execute
for user in "${Users[@]}"; do
	if [ "$user" = "$(whoami)" ]; then
		continue
	else
		uid=$(id -u "$user")

		if [[ $uid -lt 1000 ]]; then
		    echo "Skipping password change for system account: $user"
		    continue
		fi

		password $user
	fi
	if [[ " ${Allowed_Users[@]} " =~ " $user " ]]; then
		if [[ " ${Admins[@]} " =~ " $user " ]]; then
			elevate $user
		else
			demote $user
		fi
	else
		uid=$(id -u "$user")

		# If UID < 1000, skip deletion (it's a system account)
		if [[ $uid -lt 1000 ]]; then
		    echo "Skipping system account: $user"
		    continue
		fi
		
		# Otherwise safe to remove
		remove $user
	fi
done
#Root & Guest
echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
sed -i '/allow-root=true/d' /etc/lightdm/lightdm.conf

#UFW
sudo ufw enable && sudo ufw allow ssh

#Secpols
#Password
sed -i 's/^\(FAIL_LOG_ENAB\s*\).*/\Yes/' /etc/login.defs
sed -i 's/^\(LOG_OK_LOGINS\s*\).*/\Yes/' /etc/login.defs
sed -i 's/^\(LOG_UNKFAIL_ENAB\s*\).*/\Yes/' /etc/login.defs
sed -i 's/^\(SYSLOG_SU_ENAB\s*\).*/\Yes/' /etc/login.defs
sed -i 's/^\(SYSLOG_SG_ENAB\s*\).*/\Yes/' /etc/login.defs
sed -i 's/^\(PASS_MAX_DAYS\s*\).*/\90/' /etc/login.defs
sed -i 's/^\(PASS_MIN_DAYS\s*\).*/\15/' /etc/login.defs
sed -i 's/^\(PASS_WARN_AGE\s*\).*/\7/' /etc/login.defs

#IPv6
echo -e "net.ipv6.conf.all.disable_ipv6=1\nnet.ipv6.conf.default.disable_ipv6=1\nnet.ipv6.conf.lo.disable_ipv6=1" >> /etc/sysctl.conf

#Files
rm *.mp3
rm *.mp4
rm *.mov
rm *.avi

#Security Tools
sudo apt-get install fail2ban
sudo systemctl enable fail2ban
sudo systemctl start fail2ban

sudo apt-get install apparmor-utils
sudo systemctl enable apparmor
sudo systemctl start apparmor

sudo apt-get install clamav
clamscan

#Updates
sudo apt-get update && sudo apt-get upgrade -y
